In [3]:
import os
os.getcwd()


'C:\\Users\\hafize.ogut\\Downloads\\Data_Science_Algorthim'

In [5]:
!cd Dataset

In [10]:
import os
os.getcwd()


'C:\\Users\\hafize.ogut\\Downloads\\Data_Science_Algorthim'

In [20]:
import pandas as pd
df = pd.read_csv("C:\\Users\\hafize.ogut\\Downloads\\Data_Science_Algorthim\\Dataset\\Advertising.csv")
df = df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [22]:
X = df.drop('sales', axis = 1)
y = df[["sales"]]

In [24]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [26]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

# Statsmodel ile model kurmak

In [29]:
import statsmodels.api as sm


In [31]:
lm = sm.OLS(y,X)

In [33]:
model = lm.fit()

In [36]:
## scikit learn ile model kurmak

In [38]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [40]:
model = lm.fit(X,y)

In [42]:
model.intercept_

array([2.93888937])

In [44]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

# Tahmin
#### Sales = 2.94 + TV * 0.04 + 0.19 - newspaper * 0.001

30 birim tc, 10 birim raido, 40 birim gazete

In [47]:
2.94 + 30 * 0.04 + 10 *0.19-40*0.01

5.639999999999999

In [49]:
yeni_veri = [[30],[10],[40]]
yeni_veri

[[30], [10], [40]]

In [51]:
import pandas as pd
yeni_veri = pd.DataFrame(yeni_veri).T

In [52]:
yeni_veri

0   1   2
0  30  10  40

In [55]:
model.predict(yeni_veri)

C:\Users\hafize.ogut\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918]])

In [56]:
from sklearn.metrics import mean_squared_error

In [58]:
y.head() #gerçek y değerleri

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [61]:
model.predict(X)[0:10] #y^ y şapka değeri. Thmin değerleri

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [62]:
MSE = mean_squared_error(y,model.predict(X))

In [65]:
import numpy as np

RMSE = np.sqrt(MSE)

In [67]:
RMSE

1.6685701407225697

# Model Tuning (Model Doğrulama)

In [70]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [72]:
#sinama seti
from sklearn.model_selection import train_test_split

In [74]:
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size = 0.20, random_state = 99)

In [76]:
X_train

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7
..     ...    ...        ...
68   237.4   27.5       11.0
168  215.4   23.6       57.6
185  205.0   45.1       19.6
35   290.7    4.1        8.5
129   59.6   12.0       43.1

[160 rows x 3 columns]

In [78]:
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [80]:
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [82]:
lm = LinearRegression()
model = lm.fit(X_train,y_train)

In [84]:
#Eğitim Hatası
np.sqrt(mean_squared_error(y_train,model.predict(X_train)))

1.7236824822650754

In [86]:
#Test Hatası
np.sqrt(mean_squared_error(y_test,model.predict(X_test)))

1.4312783138301641

In [91]:
#k-katlı cv 

In [99]:
from sklearn.model_selection import cross_val_score
cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [103]:
#cross validaiton MSE
np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error"))

3.317028974234127

In [107]:
#cross validaiton RMSE
#cross validaiton RMSE
np.sqrt(np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")))

1.821271252239525